package cli

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/midsummer-new/midsummer-vault/internal/store"
	"github.com/spf13/cobra"
)

var envCmd = &cobra.Command{
	Use:   "env",
	Short: "Generate .env.local from vault secrets",
	Long: `Writes all vault secrets to .env.local for tools that read dotenv files.
The file is created with 0600 permissions and a DO NOT COMMIT header.

Use --format to output in different formats:
  vault env                    # writes .env.local
  vault env --format dotenv    # same as above
  vault env --format json      # JSON object
  vault env --format shell     # export KEY=value lines
  vault env --format vercel    # vercel env commands
  vault env --format netlify   # netlify env commands
  vault env --format fly       # fly secrets commands
  vault env --stdout           # print to stdout instead of writing file`,
	RunE: func(cmd *cobra.Command, args []string) error {
		env, _ := cmd.Flags().GetString("env")
		secrets := make(map[string]string)

		// load global secrets first (lower priority)
		if store.GlobalExists() {
			gs, err := store.OpenGlobalWithEnv(env)
			if err == nil {
				globalSecrets, err := gs.GetAll()
				if err == nil {
					for k, v := range globalSecrets {
						secrets[k] = v
					}
				}
			}
		}

		// load local secrets on top (higher priority)
		if store.Exists() {
			ls, err := store.OpenWithEnv(env)
			if err == nil {
				localSecrets, err := ls.GetAll()
				if err == nil {
					for k, v := range localSecrets {
						secrets[k] = v
					}
				}
			}
		}

		if len(secrets) == 0 {
			return fmt.Errorf("no secrets in vault (%s) — run `vault set KEY value` first", env)
		}

		format, _ := cmd.Flags().GetString("format")
		toStdout, _ := cmd.Flags().GetBool("stdout")

		// sort keys for deterministic output
		keys := make([]string, 0, len(secrets))
		for k := range secrets {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		var output string

		switch format {
		case "json":
			output = "{\n"
			for i, k := range keys {
				comma := ","
				if i == len(keys)-1 {
					comma = ""
				}
				output += fmt.Sprintf("  %q: %q%s\n", k, secrets[k], comma)
			}
			output += "}\n"

		case "shell":
			for _, k := range keys {
				output += fmt.Sprintf("export %s=%q\n", k, secrets[k])
			}

		case "vercel":
			for _, k := range keys {
				// vercel env add KEY production < value
				output += fmt.Sprintf("echo %q | vercel env add %s production\n", secrets[k], k)
			}

		case "netlify":
			for _, k := range keys {
				output += fmt.Sprintf("netlify env:set %s %q\n", k, secrets[k])
			}

		case "fly":
			var pairs []string
			for _, k := range keys {
				pairs = append(pairs, fmt.Sprintf("%s=%q", k, secrets[k]))
			}
			output = fmt.Sprintf("fly secrets set %s\n", strings.Join(pairs, " "))

		default: // dotenv
			output = "# Generated by vault — DO NOT COMMIT\n\n"
			for _, k := range keys {
				output += fmt.Sprintf("%s=%s\n", k, secrets[k])
			}
		}

		if toStdout {
			fmt.Print(output)
			return nil
		}

		// for platform formats, always stdout (they're commands to run, not files)
		if format == "vercel" || format == "netlify" || format == "fly" || format == "shell" || format == "json" {
			fmt.Print(output)
			return nil
		}

		// write .env.local
		if err := os.WriteFile(".env.local", []byte(output), 0600); err != nil {
			return fmt.Errorf("failed to write .env.local: %w", err)
		}

		fmt.Printf("✓ Wrote %d secrets to .env.local\n", len(secrets))
		return nil
	},
}

func init() {
	envCmd.Flags().String("format", "dotenv", "Output format: dotenv, json, shell, vercel, netlify, fly")
	envCmd.Flags().Bool("stdout", false, "Print to stdout instead of writing .env.local")
	envCmd.Flags().String("env", store.DefaultEnv, "Target environment (development, staging, production)")
}
