package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var pullCmd = &cobra.Command{
	Use:   "pull",
	Short: "Pull secrets into .env.local.vault",
	RunE: func(cmd *cobra.Command, args []string) error {
		cr, err := getClientAndProject()
		if err != nil {
			return err
		}

		secrets, err := cr.client.GetSecrets(cr.projectID)
		if err != nil {
			return fmt.Errorf("failed to fetch secrets: %w", err)
		}

		var b strings.Builder
		b.WriteString("# Generated by midsummer-vault — DO NOT COMMIT\n\n")
		for k, v := range secrets {
			b.WriteString(fmt.Sprintf("%s=%s\n", k, v))
		}

		if err := os.WriteFile(".env.local.vault", []byte(b.String()), 0600); err != nil {
			return fmt.Errorf("failed to write .env.local.vault: %w", err)
		}

		fmt.Printf("✓ Wrote %d secrets to .env.local.vault\n", len(secrets))
		return nil
	},
}
